# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c4a020a88ce038e2220cb08a3a31ccbc612129ef04cae1cf91361cd454336f3cf7262e90e5995adcc1ca66abe4948945e595f1dfa6126433058609b024a5a2

test:
  secret_key_base: 49ef4e7ada3be25fc8158221278da17124dd04d6bee7d306c30ed06be06c8b63429e9cf32465852ac500b27c980f8436aafdf640838d1bfa2f42e6ab9680ed5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
